dist: xenial

language: go

go:
  - 1.12.x

sudo: false

env:
  - GO111MODULE=on

install:
  - echo $TRAVIS_GO_VERSION
  - make mod-dl
  - python --version
  - pip --version
  - pip install --user awscli
  - pip install --user aws-sam-cli

script:
  - make ci
  - make validate
  - make package

deploy:
  provider: script
  script: make deploy
  skip_cleanup: true
  on:
    branch: master

notifications:
  email:
    on_success: never
