AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'misc-functions-http-go1

  Sample SAM Template for misc-functions-http-go1

  '
Parameters:
  KeyIdParameter:
    Type: String
Globals:
  Function:
    Timeout: 10
    Environment:
      Variables:
        KMS_REGION: ap-northeast-1
Resources:
  MiscGoAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://jpshadowapps-lambdas/misc-functions-http-go1/ff42d61397c2f24a8d2ad8d3c56aa77b
      Handler: miscfunc
      Runtime: go1.x
      Tracing: Active
      Policies:
      - KMSDecryptPolicy:
          KeyId:
            Ref: KeyIdParameter
      - DynamoDBCrudPolicy:
          TableName:
            Ref: WorkstatusDynamoDBTable
      Environment:
        Variables:
          DYNAMO_TABLE_NAME:
            Ref: WorkstatusDynamoDBTable
          USE_LOCAL_DYNAMO: 'false'
      Events:
        GetHello:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
        PostWorkstatus:
          Type: Api
          Properties:
            Path: /workstatus
            Method: POST
        DescWorkstatus:
          Type: Api
          Properties:
            Path: /workstatus
            Method: GET
        GetCrawler:
          Type: Api
          Properties:
            Path: /crawler
            Method: GET
  WorkstatusDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: ID
        AttributeType: S
      - AttributeName: Content
        AttributeType: S
      KeySchema:
      - AttributeName: ID
        KeyType: HASH
      - AttributeName: Content
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
Outputs:
  MiscGoAPI:
    Description: API Gateway endpoint URL for Prod environment for First Function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/
  MiscGoAPIFunction:
    Description: First Lambda Function ARN
    Value:
      Fn::GetAtt:
      - MiscGoAPIFunction
      - Arn
  WorkstatusDynamoDBTable:
    Description: Workstatus DynamoDB Table
    Value:
      Fn::GetAtt:
      - WorkstatusDynamoDBTable
      - Arn
