AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  misc-functions-http-go1
  
  Sample SAM Template for misc-functions-http-go1

# See: https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html
Parameters:
  KeyIdParameter:
    Type: String

# See: https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/mappings-section-structure.html
# Mappings:
#   HogeMap:
#     hoge1:
#       hoge1key1: "hoge1value1"

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
      Variables:
        KMS_REGION: ap-northeast-1

Resources:
  MiscGoAPIFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: miscfunc/
      Handler: miscfunc
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Policies: # More info: https://github.com/awslabs/serverless-application-model/blob/master/examples/2016-10-31/policy_templates/all_policy_templates.yaml
        - KMSDecryptPolicy:
            KeyId: !Ref KeyIdParameter
        - DynamoDBCrudPolicy:
            TableName: !Ref WorkstatusDynamoDBTable
      Environment:
        Variables:
          DYNAMO_TABLE_NAME: !Ref WorkstatusDynamoDBTable
          USE_LOCAL_DYNAMO: "false"
      Events:
        GetHello:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
        PostWorkstatus:
          Type: Api
          Properties:
            Path: /workstatus
            Method: POST
        DescWorkstatus:
          Type: Api
          Properties:
            Path: /workstatus
            Method: GET
        GetCrawler:
          Type: Api
          Properties:
            Path: /crawler
            Method: GET
  WorkstatusDynamoDBTable:
    # See: https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: ID
          AttributeType: S
        - AttributeName: Content
          AttributeType: S
      KeySchema:
        - AttributeName: ID
          KeyType: HASH
        - AttributeName: Content
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

# See: https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html
Outputs:
  MiscGoAPI:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  MiscGoAPIFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt MiscGoAPIFunction.Arn
  WorkstatusDynamoDBTable:
    Description: "Workstatus DynamoDB Table"
    Value: !GetAtt WorkstatusDynamoDBTable.Arn
